set -e
true
true
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/spades-hammer /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/corrected/configs/config.info
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/python3 /Users/kimberlyhabon/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/corrected/corrected.yaml --ext_python_modules_home /Users/kimberlyhabon/miniconda3/envs/genomeanalysis/share/spades --max_threads 16 --output_dir /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/corrected --gzip_output
true
true
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/spades-core /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K21/configs/config.info
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/spades-core /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K33/configs/config.info
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/spades-core /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K55/configs/config.info
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/spades-core /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/configs/config.info
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/python3 /Users/kimberlyhabon/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/before_rr.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/before_rr.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/assembly_graph_after_simplification.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/assembly_graph_after_simplification.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/final_contigs.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/contigs.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/first_pe_contigs.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/first_pe_contigs.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/strain_graph.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/strain_graph.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/scaffolds.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/scaffolds.fasta /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/scaffolds.paths /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/scaffolds.paths /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/assembly_graph_with_scaffolds.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/assembly_graph_with_scaffolds.gfa /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/assembly_graph.fastg /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/assembly_graph.fastg /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/K77/final_contigs.paths /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/contigs.paths
true
/Users/kimberlyhabon/miniconda3/envs/genomeanalysis/bin/python3 /Users/kimberlyhabon/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/scaffolds.fasta --misc_dir /Users/kimberlyhabon/Desktop/Genomeanalysisfinalproject/spadesout/misc --threshold_for_breaking_scaffolds 3
true
